name = "notesheet-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Uncomment and fill in after creating D1 database:
# wrangler d1 create notesheet
[[d1_databases]]
binding = "DB"
database_name = "notesheet"
database_id = "7462403d-35f0-4a56-aeb3-cb397bf2f478"

# Uncomment and fill in after creating KV namespace:
# wrangler kv:namespace create TOKENS
# [[kv_namespaces]]
# binding = "TOKENS"
# id = "YOUR_KV_NAMESPACE_ID"
